window.MARYILU_DATA = (() => {
    const leadStatuses = [
        "New request",
        "Direction needed",
        "Concept sent",
        "Concept approved",
        "Deposit paid",
        "In progress",
        "Progress update sent",
        "Awaiting final approval",
        "Final payment pending",
        "Ready for pickup/shipping",
        "Completed",
        "Review requested"
    ];

    const categoryMeta = [
        {
            id: "canvases",
            publicCategory: { en: "Custom Canvases", es: "Lienzos personalizados" },
            shortName: { en: "Canvases", es: "Lienzos" },
            priceFrom: "from €90",
            summary: {
                en: "Painted wall art, lyrics, portraits, quotes, and memory pieces.",
                es: "Arte para pared, letras, retratos, frases y recuerdos pintados a mano."
            }
        },
        {
            id: "flowers",
            publicCategory: { en: "Handmade Flower Bouquets", es: "Ramos de flores hechos a mano" },
            shortName: { en: "Flowers", es: "Flores" },
            priceFrom: "from €10",
            summary: {
                en: "Ribbon flowers and romantic bouquets made to match the occasion.",
                es: "Flores de cinta y ramos románticos para la ocasión."
            }
        },
        {
            id: "gift-boxes",
            publicCategory: { en: "Custom Gift Boxes & Chests", es: "Cajas y cofres personalizados" },
            shortName: { en: "Gift Boxes & Chests", es: "Cajas y cofres" },
            priceFrom: "from €49",
            summary: {
                en: "The main custom gift format: chests, birthday boxes, memory boxes, and surprise boxes.",
                es: "El formato principal: cofres, cajas de cumpleaños, cajas de recuerdos y sorpresas."
            }
        },
        {
            id: "baby-shower",
            publicCategory: { en: "Baby Shower Gifts", es: "Regalos para baby shower" },
            shortName: { en: "Baby Shower", es: "Baby shower" },
            priceFrom: "from €49",
            summary: {
                en: "Diaper cakes, baby gift towers, and soft celebration pieces.",
                es: "Tartas de pañales, torres de regalo y detalles dulces para celebrar."
            }
        }
    ];

    const products = [
        {
            category: "canvases",
            publicCategory: categoryMeta[0].publicCategory,
            name: { en: "Mini Canvas", es: "Lienzo mini" },
            size: "20 x 25 cm",
            priceFrom: "from €90",
            priceNote: { en: "Custom price depending on image/detail", es: "Precio según imagen y nivel de detalle" },
            productionTime: "3-5 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A small personal canvas for simple names, symbols, quotes, and minimal designs.", es: "Un lienzo pequeño para nombres, símbolos, frases y diseños minimalistas." },
            bestFor: { en: "Simple names, symbols, quotes, small illustrations, minimal designs", es: "Nombres simples, símbolos, frases, ilustraciones pequeñas y diseños minimalistas" },
            enabled: true,
            standby: false
        },
        {
            category: "canvases",
            publicCategory: categoryMeta[0].publicCategory,
            name: { en: "Standard Canvas", es: "Lienzo estándar" },
            size: "30 x 40 cm",
            priceFrom: "from €120",
            priceNote: { en: "Custom price depending on image/detail", es: "Precio según imagen y nivel de detalle" },
            productionTime: "5-7 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A flexible size for portraits, pets, couple gifts, song lyrics, and moderate detail.", es: "Un tamaño flexible para retratos, mascotas, regalos de pareja, letras de canciones y detalle medio." },
            bestFor: { en: "Portraits, couple gifts, pets, song lyrics, moderate detail", es: "Retratos, regalos de pareja, mascotas, letras de canciones y detalle medio" },
            enabled: true,
            standby: false
        },
        {
            category: "canvases",
            publicCategory: categoryMeta[0].publicCategory,
            name: { en: "Detailed Canvas", es: "Lienzo detallado" },
            size: "40 x 50 cm",
            priceFrom: "from €170",
            priceNote: { en: "Custom price depending on image/detail", es: "Precio según imagen y nivel de detalle" },
            productionTime: "7-10 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A larger custom piece for layered themes, backgrounds, and multiple elements.", es: "Una pieza más grande para temas con capas, fondos y varios elementos." },
            bestFor: { en: "Detailed portraits, backgrounds, multiple elements, complex themes", es: "Retratos detallados, fondos, varios elementos y temas complejos" },
            enabled: true,
            standby: false
        },
        {
            category: "canvases",
            publicCategory: categoryMeta[0].publicCategory,
            name: { en: "Large Premium Canvas", es: "Lienzo premium grande" },
            size: "50 x 70 cm",
            priceFrom: "from €210-€270",
            priceNote: { en: "Custom price depending on image/detail", es: "Precio según imagen y nivel de detalle" },
            productionTime: "10-14 days",
            shippingNote: { en: "Free standard EU shipping if order is over €150 and parcel size allows", es: "Envío estándar gratis en la UE si supera €150 y el paquete lo permite" },
            description: { en: "A statement canvas for premium wall art and detailed custom scenes.", es: "Un lienzo protagonista para pared y escenas personalizadas con detalle." },
            bestFor: { en: "Premium wall art, detailed custom scenes, larger portraits, statement gifts", es: "Arte premium, escenas detalladas, retratos grandes y regalos protagonistas" },
            enabled: true,
            standby: false
        },
        {
            category: "canvases",
            publicCategory: categoryMeta[0].publicCategory,
            name: { en: "Extra Large Canvas", es: "Lienzo extra grande" },
            size: "60 x 80 cm or larger",
            priceFrom: "custom quote",
            priceNote: { en: "Quoted after reviewing size, detail, and shipping", es: "Presupuesto según tamaño, detalle y envío" },
            productionTime: "custom timeline",
            shippingNote: { en: "Custom quote only", es: "Solo con presupuesto de envío" },
            description: { en: "Oversized custom art for larger spaces or complex scenes.", es: "Arte personalizado grande para espacios amplios o escenas complejas." },
            bestFor: { en: "Large portraits, complex themes, statement wall art", es: "Retratos grandes, temas complejos y arte protagonista" },
            enabled: true,
            standby: false
        },
        {
            category: "flowers",
            publicCategory: categoryMeta[1].publicCategory,
            name: { en: "1 Ribbon Flower", es: "1 flor de cinta" },
            size: "1 flower",
            priceFrom: "€10 plus extras",
            priceNote: { en: "Extras priced separately", es: "Extras aparte" },
            productionTime: "around 30 minutes",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A single handmade ribbon flower for a sweet personal detail.", es: "Una flor de cinta hecha a mano para un detalle pequeño y personal." },
            bestFor: { en: "Small gifts, add-ons, simple romantic details", es: "Detalles pequeños, extras y regalos románticos simples" },
            enabled: true,
            standby: false
        },
        {
            category: "flowers",
            publicCategory: categoryMeta[1].publicCategory,
            name: { en: "Little Ribbon Bouquet", es: "Ramo pequeño de cinta" },
            size: "3 flowers",
            priceFrom: "from €30 plus extras",
            priceNote: { en: "Confirm production time with Maryilu", es: "Confirmar tiempo con Maryilu" },
            productionTime: "4-6 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A small bouquet with handmade ribbon flowers and optional details.", es: "Un ramo pequeño con flores de cinta y detalles opcionales." },
            bestFor: { en: "Small celebrations, thank-you gifts, romantic mini bouquets", es: "Celebraciones pequeñas, agradecimientos y mini ramos románticos" },
            enabled: true,
            standby: false
        },
        {
            category: "flowers",
            publicCategory: categoryMeta[1].publicCategory,
            name: { en: "Standard Ribbon Bouquet", es: "Ramo estándar de cinta" },
            size: "6 flowers",
            priceFrom: "from €70 plus extras",
            priceNote: { en: "Extras priced separately", es: "Extras aparte" },
            productionTime: "5-8 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A fuller handmade bouquet made around colors, occasion, and style.", es: "Un ramo más completo según colores, ocasión y estilo." },
            bestFor: { en: "Birthdays, anniversaries, romantic gifts", es: "Cumpleanos, aniversarios y regalos románticos" },
            enabled: true,
            standby: false
        },
        {
            category: "flowers",
            publicCategory: categoryMeta[1].publicCategory,
            name: { en: "Large Ribbon Bouquet", es: "Ramo grande de cinta" },
            size: "9 flowers",
            priceFrom: "from €95 plus extras",
            priceNote: { en: "Extras priced separately", es: "Extras aparte" },
            productionTime: "7-10 days",
            shippingNote: { en: "Free standard EU shipping if parcel size allows", es: "Envío estándar gratis en la UE si el paquete lo permite" },
            description: { en: "A dramatic handmade bouquet with a stronger visual impact.", es: "Un ramo hecho a mano con más presencia visual." },
            bestFor: { en: "Statement bouquet gifts and themed arrangements", es: "Ramos protagonistas y arreglos tematicos" },
            enabled: true,
            standby: false
        },
        {
            category: "flowers",
            publicCategory: categoryMeta[1].publicCategory,
            name: { en: "Custom Ribbon Bouquet", es: "Ramo personalizado de cinta" },
            size: "9+ flowers",
            priceFrom: "on request",
            priceNote: { en: "Quoted by size and extras", es: "Presupuesto según tamaño y extras" },
            productionTime: "custom timeline",
            shippingNote: { en: "Custom quote depending on size", es: "Presupuesto según tamaño" },
            description: { en: "A fully customized bouquet for a specific theme, color palette, or story.", es: "Un ramo totalmente personalizado por tema, paleta o historia." },
            bestFor: { en: "Large custom themes, premium gifts, special occasions", es: "Temas grandes, regalos premium y ocasiones especiales" },
            enabled: true,
            standby: false
        },
        {
            category: "flowers",
            publicCategory: categoryMeta[1].publicCategory,
            name: { en: "Bead Flower", es: "Flor de cuentas" },
            size: "1 flower",
            priceFrom: "from €69",
            priceNote: { en: "Standby for MVP", es: "En espera para MVP" },
            productionTime: "4-6 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "Future bead flower option.", es: "Opcion futura de flor de cuentas." },
            bestFor: { en: "Future launch", es: "Lanzamiento futuro" },
            enabled: false,
            standby: true
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Mini Custom Chest", es: "Cofre personalizado mini" },
            size: "20 x 20 x 10 cm",
            priceFrom: "standby",
            priceNote: { en: "Hidden until price is confirmed", es: "Oculto hasta confirmar precio" },
            productionTime: "4-7 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "Standby chest tier.", es: "Cofre en espera." },
            bestFor: { en: "Future launch", es: "Lanzamiento futuro" },
            enabled: false,
            standby: true
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Standard Custom Chest", es: "Cofre personalizado estándar" },
            size: "30 x 20 x 18 cm",
            priceFrom: "from €159",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "7-10 days",
            shippingNote: { en: "Free standard EU shipping", es: "Envío estándar gratis en la UE" },
            description: { en: "A story-led custom chest with handmade decoration and selected details.", es: "Un cofre personalizado con decoración hecha a mano y detalles elegidos." },
            bestFor: { en: "Birthdays, anniversaries, memory gifts, surprise boxes", es: "Cumpleanos, aniversarios, recuerdos y sorpresas" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Premium Custom Chest", es: "Cofre personalizado premium" },
            size: "40 x 30 x 25 cm",
            priceFrom: "from €229-€299",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "10-14 days",
            shippingNote: { en: "Free standard EU shipping if parcel size allows", es: "Envío estándar gratis en la UE si el paquete lo permite" },
            description: { en: "A more elaborate chest with stronger theme, scale, and detail.", es: "Un cofre más elaborado con más tema, escala y detalle." },
            bestFor: { en: "Premium personal gifts and detailed surprise chests", es: "Regalos personales premium y cofres sorpresa detallados" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Large Custom Chest", es: "Cofre personalizado grande" },
            size: "50 x 35 x 30 cm or larger",
            priceFrom: "from €350+",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "14+ days",
            shippingNote: { en: "Custom quote only", es: "Solo con presupuesto de envío" },
            description: { en: "A large custom chest for complex stories and premium gifting.", es: "Un cofre grande para historias complejas y regalos premium." },
            bestFor: { en: "Large surprises, many memories, premium themes", es: "Grandes sorpresas, muchos recuerdos y temas premium" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Mini Birthday Box", es: "Caja de cumpleaños mini" },
            size: "20 x 20 x 10 cm",
            priceFrom: "from €49",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "2-4 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A small birthday box with personalized handmade touches.", es: "Una caja pequena de cumpleaños con detalles personalizados." },
            bestFor: { en: "Small birthdays, quick personal gifts", es: "Cumpleanos pequeños y regalos personales rapidos" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Standard Birthday Box", es: "Caja de cumpleaños estándar" },
            size: "25 x 25 x 12 cm",
            priceFrom: "from €89",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "4-6 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A balanced birthday box with more space for memories and details.", es: "Una caja equilibrada con más espacio para recuerdos y detalles." },
            bestFor: { en: "Birthday surprises and themed gifts", es: "Sorpresas de cumpleaños y regalos tematicos" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Signature Birthday Box", es: "Caja de cumpleaños signature" },
            size: "30 x 30 x 15 cm",
            priceFrom: "from €129",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "5-8 days",
            shippingNote: { en: "Paid by buyer unless total order is over €150", es: "Envío a cargo del comprador salvo pedidos sobre €150" },
            description: { en: "A richer birthday box for a more memorable reveal.", es: "Una caja más completa para una sorpresa más memorable." },
            bestFor: { en: "Personal birthday stories, memories, hobbies, and color themes", es: "Historias personales, recuerdos, hobbies y paletas de color" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Premium Birthday Box", es: "Caja de cumpleaños premium" },
            size: "35 x 35 x 20 cm",
            priceFrom: "from €169-€219",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "7-10 days",
            shippingNote: { en: "Free standard EU shipping if parcel size allows", es: "Envío estándar gratis en la UE si el paquete lo permite" },
            description: { en: "A premium birthday box with more volume, theme, and handmade details.", es: "Una caja premium con más volumen, tema y detalles hechos a mano." },
            bestFor: { en: "Premium birthday gifts and elaborate surprises", es: "Regalos premium de cumpleaños y sorpresas elaboradas" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Oversized Birthday Box", es: "Caja de cumpleaños extra grande" },
            size: "40 x 40 x 25 cm or larger",
            priceFrom: "custom quote",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "custom timeline",
            shippingNote: { en: "Custom quote only", es: "Solo con presupuesto de envío" },
            description: { en: "A large birthday box quoted by size, fragility, and contents.", es: "Una caja grande con presupuesto según tamaño, fragilidad y contenido." },
            bestFor: { en: "Large gifts and oversized surprises", es: "Regalos grandes y sorpresas extra grandes" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Simple Custom Gift Box", es: "Caja personalizada simple" },
            size: "20 x 20 x 10 cm",
            priceFrom: "from €79",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "3-5 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A simple custom box shaped around one clear idea or theme.", es: "Una caja simple alrededor de una idea o tema claro." },
            bestFor: { en: "Small personal gifts and focused themes", es: "Regalos personales pequeños y temas concretos" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Standard Custom Gift Box", es: "Caja personalizada estándar" },
            size: "25 x 25 x 12 cm",
            priceFrom: "from €129",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "5-7 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A custom box with room for more story, color, and handmade elements.", es: "Una caja personalizada con más historia, color y elementos hechos a mano." },
            bestFor: { en: "Memories, interests, romantic gifts, friendship gifts", es: "Recuerdos, intereses, regalos románticos y amistad" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Signature Custom Gift Box", es: "Caja personalizada signature" },
            size: "30 x 30 x 15 cm",
            priceFrom: "from €179",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "7-10 days",
            shippingNote: { en: "Free standard EU shipping", es: "Envío estándar gratis en la UE" },
            description: { en: "A signature gift box with a detailed theme and stronger handmade presentation.", es: "Una caja signature con tema detallado y presentacion artesanal más fuerte." },
            bestFor: { en: "Detailed custom stories and memorable reveals", es: "Historias personalizadas detalladas y sorpresas memorables" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Premium Custom Gift Box", es: "Caja personalizada premium" },
            size: "35 x 35 x 20 cm",
            priceFrom: "from €229-€299",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "10-14 days",
            shippingNote: { en: "Free standard EU shipping if parcel size allows", es: "Envío estándar gratis en la UE si el paquete lo permite" },
            description: { en: "A premium custom box with more volume, materials, and personal detail.", es: "Una caja premium con más volumen, materiales y detalle personal." },
            bestFor: { en: "Premium handmade gifts and layered themes", es: "Regalos handmade premium y temas con capas" },
            enabled: true,
            standby: false
        },
        {
            category: "gift-boxes",
            publicCategory: categoryMeta[2].publicCategory,
            name: { en: "Luxury Custom Gift Box", es: "Caja personalizada luxury" },
            size: "40 x 40 x 25 cm or larger",
            priceFrom: "from €350+",
            priceNote: { en: "Extra purchased items inside are charged separately", es: "Articulos comprados para dentro se cobran aparte" },
            productionTime: "14+ days",
            shippingNote: { en: "Custom quote only", es: "Solo con presupuesto de envío" },
            description: { en: "A large-scale custom gift experience quoted around the full concept.", es: "Una experiencia de regalo a gran escala con presupuesto por concepto completo." },
            bestFor: { en: "Luxury handmade gifts, oversized themes, complex reveals", es: "Regalos luxury, temas grandes y sorpresas complejas" },
            enabled: true,
            standby: false
        },
        {
            category: "baby-shower",
            publicCategory: categoryMeta[3].publicCategory,
            name: { en: "Mini Diaper Cake", es: "Tarta de pañales mini" },
            size: "20 cm diameter x 25 cm tall; approx 15-25 diapers",
            priceFrom: "from €49",
            priceNote: { en: "Final price depends on decoration and extras", es: "Precio según decoración y extras" },
            productionTime: "2-4 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A small baby shower piece with decorative handmade details.", es: "Un detalle pequeño de baby shower con decoración hecha a mano." },
            bestFor: { en: "Small baby shower gifts and table displays", es: "Regalos pequeños y decoración de mesa" },
            enabled: true,
            standby: false
        },
        {
            category: "baby-shower",
            publicCategory: categoryMeta[3].publicCategory,
            name: { en: "Standard Diaper Cake", es: "Tarta de pañales estándar" },
            size: "25 cm diameter x 35 cm tall; approx 30-45 diapers",
            priceFrom: "from €89",
            priceNote: { en: "Final price depends on decoration and extras", es: "Precio según decoración y extras" },
            productionTime: "4-6 days",
            shippingNote: { en: "Paid by buyer", es: "Envío a cargo del comprador" },
            description: { en: "A balanced baby shower gift with more height and decorative presence.", es: "Un regalo equilibrado con más altura y presencia decorativa." },
            bestFor: { en: "Baby showers, family gifts, nursery-themed surprises", es: "Baby showers, regalos familiares y detalles de habitacion" },
            enabled: true,
            standby: false
        },
        {
            category: "baby-shower",
            publicCategory: categoryMeta[3].publicCategory,
            name: { en: "Premium Diaper Cake", es: "Tarta de pañales premium" },
            size: "30 cm diameter x 45 cm tall; approx 50-70 diapers",
            priceFrom: "from €139",
            priceNote: { en: "Final price depends on decoration and extras", es: "Precio según decoración y extras" },
            productionTime: "5-8 days",
            shippingNote: { en: "Paid by buyer unless total order is over €150 and parcel size allows", es: "Envío a cargo del comprador salvo pedidos sobre €150 si el paquete lo permite" },
            description: { en: "A fuller baby gift with a stronger decorative look.", es: "Un regalo de bebé más completo y decorativo." },
            bestFor: { en: "Premium baby shower gifts and larger celebrations", es: "Regalos premium de baby shower y celebraciones grandes" },
            enabled: true,
            standby: false
        },
        {
            category: "baby-shower",
            publicCategory: categoryMeta[3].publicCategory,
            name: { en: "Large Baby Gift Tower", es: "Torre grande de regalo para bebé" },
            size: "35 cm diameter x 55 cm tall; approx 80+ diapers",
            priceFrom: "from €179-€229",
            priceNote: { en: "Final price depends on decoration and extras", es: "Precio según decoración y extras" },
            productionTime: "7-10 days",
            shippingNote: { en: "Custom quote if oversized", es: "Presupuesto si es grande" },
            description: { en: "A tall baby shower statement piece with layered decoration.", es: "Una pieza protagonista de baby shower con decoración por capas." },
            bestFor: { en: "Large baby shower gifts and display pieces", es: "Regalos grandes y piezas decorativas principales" },
            enabled: true,
            standby: false
        }
    ];

    const addOns = [
        { name: { en: "Custom handwritten card", es: "Tarjeta escrita a mano" }, price: "€8-€15" },
        { name: { en: "Custom painted name tag", es: "Etiqueta pintada con nombre" }, price: "€10-€20" },
        { name: { en: "Small handmade charm/detail", es: "Charm o detalle hecho a mano" }, price: "€10-€25" },
        { name: { en: "Song lyric page or mini booklet", es: "Pagina de letra o mini librito" }, price: "€25-€60" },
        { name: { en: "Photo/memory decoration", es: "Decoracion con foto o recuerdo" }, price: "€15-€40" },
        { name: { en: "Extra sourced gift items", es: "Regalos comprados extra" }, price: { en: "item cost + sourcing/design fee", es: "coste del artículo + gestion/diseño" } },
        { name: { en: "Rush order fee", es: "Recargo urgente" }, price: "+20% to +40%" }
    ];

    const shippingPolicy = [
        { title: { en: "Mallorca", es: "Mallorca" }, lines: [{ en: "Local pickup: free", es: "Recogida local: gratis" }, { en: "Local delivery in Mallorca: €5-€15 depending on area", es: "Entrega local en Mallorca: €5-€15 según zona" }] },
        { title: { en: "Spain Mainland", es: "España peninsula" }, lines: [{ en: "Small items: €8-€12", es: "Piezas pequeñas: €8-€12" }, { en: "Medium boxes: €12-€18", es: "Cajas medianas: €12-€18" }, { en: "Large or fragile pieces: custom quote", es: "Piezas grandes o fragiles: presupuesto" }] },
        { title: { en: "European Union", es: "Union Europea" }, lines: [{ en: "Small/light items: €15-€25", es: "Piezas pequeñas/ligeras: €15-€25" }, { en: "Medium parcels: €25-€40", es: "Paquetes medianos: €25-€40" }, { en: "Large, fragile, or heavy parcels: custom quote", es: "Paquetes grandes, fragiles o pesados: presupuesto" }] },
        { title: { en: "Free EU Shipping", es: "Envío gratis UE" }, lines: [{ en: "Available on orders over €150 when the packed parcel is not oversized or unusually heavy.", es: "Disponible en pedidos sobre €150 si el paquete no es grande ni pesado." }, { en: "Approximate limit: under 50 x 40 x 35 cm and under 3 kg.", es: "Limite aproximado: menos de 50 x 40 x 35 cm y menos de 3 kg." }, { en: "Oversized, fragile, heavy, or express orders may still need a quote.", es: "Pedidos grandes, fragiles, pesados o express pueden necesitar presupuesto." }] },
        { title: { en: "USA & International", es: "EE. UU. e internacional" }, lines: [{ en: "Accepted on request and quoted separately before payment.", es: "Disponible bajo pedido y con presupuesto antes del pago." }, { en: "International buyers are responsible for customs, import taxes, or handling fees.", es: "El comprador internacional asume aduanas, impuestos y tasas." }] }
    ];

    const faqs = [
        { q: { en: "Do I need to know exactly what I want?", es: "Tengo que saber exactamente lo que quiero?" }, a: { en: "No. Tell me about the person, the occasion, your budget, and the style. I can help suggest the best idea.", es: "No. Cuéntame sobre la persona, la ocasión, tu presupuesto y el estilo. Yo te ayudo a dar forma a la idea." } },
        { q: { en: "Can I give detailed direction?", es: "Puedo dar instrucciones detalladas?" }, a: { en: "Yes. References, colors, photos, themes, songs, quotes, memories, and anything important are welcome.", es: "Sí. Puedes compartir referencias, colores, fotos, temas, canciones, frases, recuerdos y cualquier detalle importante." } },
        { q: { en: "Will I get progress updates?", es: "Recibiré avances del proceso?" }, a: { en: "For detailed pieces, yes. I can send updates during the process to make sure the direction feels right.", es: "Para piezas detalladas, si. Puedo enviar avances durante el proceso para asegurar que vamos en la dirección correcta." } },
        { q: { en: "How much does a custom gift cost?", es: "Cuánto cuesta un regalo personalizado?" }, a: { en: "Prices start from €10 for a single ribbon flower, €49 for small gift boxes or baby gifts, and €90 for custom canvases. Larger custom gifts and chests usually range from €129 to €350+.", es: "Los precios empiezan desde €10 por una flor de cinta, €49 por cajas pequeñas o regalos de bebé, y €90 por lienzos personalizados. Regalos y cofres más grandes suelen ir de €129 a €350+." } },
        { q: { en: "Do you require a deposit?", es: "Se necesita depósito?" }, a: { en: "Yes. Custom orders require a 50% deposit before work begins.", es: "Sí. Los pedidos personalizados requieren un depósito del 50% antes de empezar." } },
        { q: { en: "Can I cancel?", es: "Puedo cancelar?" }, a: { en: "Because every piece is custom handmade, cancellations are not accepted once work has started.", es: "Como cada pieza es personalizada y hecha a mano, no se aceptan cancelaciones una vez empezado el trabajo." } },
        { q: { en: "Do you ship?", es: "Haces envíos?" }, a: { en: "Yes. Mallorca pickup/delivery, Spain shipping, and EU shipping are available. U.S. and international orders are quoted separately.", es: "Sí. Hay recogida/entrega en Mallorca, envíos a España y a la UE. EE. UU. e internacional se presupuestan aparte." } },
        { q: { en: "Is free shipping available?", es: "Hay envío gratis?" }, a: { en: "Free standard EU shipping is available on orders over €150, as long as the packed parcel is not oversized, fragile, or unusually heavy.", es: "El envío estándar gratis en la UE está disponible en pedidos sobre €150, siempre que el paquete no sea grande, fragil o muy pesado." } }
    ];

    const studioInspirationItems = [
        {
            id: "studio-inspiration-chest",
            category: "gift-boxes",
            title: { en: "Painted keepsake chest", es: "Cofre recuerdo pintado" },
            caption: { en: "A hand-painted box built around one person, one occasion, and the details they will recognize.", es: "Una caja pintada a mano alrededor de una persona, una ocasión y detalles que reconocerá." }
        },
        {
            id: "studio-inspiration-bouquet",
            category: "flowers",
            title: { en: "Ribbon bouquet gift", es: "Ramo de cinta regalo" },
            caption: { en: "Permanent flowers with custom colors, names, cards, or small details matched to the recipient.", es: "Flores permanentes con colores, nombres, tarjetas o detalles elegidos para la persona." }
        },
        {
            id: "studio-inspiration-canvas",
            category: "canvases",
            title: { en: "Personal memory canvas", es: "Lienzo de recuerdo personal" },
            caption: { en: "Lyrics, quotes, portraits, symbols, and colors turned into wall art.", es: "Letras, frases, retratos, símbolos y colores convertidos en arte para pared." }
        },
        {
            id: "studio-inspiration-baby-gift",
            category: "baby-shower",
            title: { en: "Baby shower keepsake gift", es: "Regalo recuerdo baby shower" },
            caption: { en: "A decorative handmade baby gift with soft colors, keepsake details, and a quote before payment.", es: "Un regalo decorativo hecho a mano para bebé con colores suaves, detalles recuerdo y presupuesto antes de pagar." }
        }
    ];

    // Portfolio gallery source. To add real artworks, append objects with the same
    // shape (id, title, year, medium, size, description, imageUrl). The portfolio
    // gallery, lightbox, bento layout, and scroll-reveal all scale automatically —
    // no JS changes needed. Drop optimized images in /assets and reference the .png
    // (matching .webp/.avif are picked up via <picture> when present).
    const portfolioWorks = [
        {
            id: "portfolio-painted-chest",
            title: "Painted keepsake object",
            year: "2026",
            medium: "Painted object",
            size: "One of one",
            description: "A functional object treated like a small painting: floral detail, shadow, and shine.",
            imageUrl: "assets/maryilu-luxury-chest-hero.png"
        },
        {
            id: "portfolio-ribbon-color",
            title: "Ribbon color composition",
            year: "2026",
            medium: "Handmade textile work",
            size: "Object study",
            description: "Ribbon flowers and painted surfaces arranged as a bright, tactile study.",
            imageUrl: "assets/maryilu-editorial-store-hero.png"
        },
        {
            id: "portfolio-studio-wall",
            title: "Studio wall and works",
            year: "2026",
            medium: "Mixed media studio view",
            size: "Series view",
            description: "Paintings, portraits, florals, and color studies shown together in the studio.",
            imageUrl: "assets/maria-luisa-portfolio-studio.png"
        },
        {
            id: "portfolio-floral-panel",
            title: "Floral panel study",
            year: "2026",
            medium: "Floral painting study",
            size: "Color archive",
            description: "Soft petals, dark stems, and open negative space used as a study in tenderness and contrast.",
            imageUrl: "assets/maria-luisa-portfolio-studio.png"
        },
        {
            id: "portfolio-gift-detail",
            title: "Keepsake detail study",
            year: "2026",
            medium: "Painted gift object",
            size: "Detail view",
            description: "A closer look at the ornamental language Maryilu uses for memory-led handmade gifts.",
            imageUrl: "assets/maryilu-luxury-chest-hero.png"
        },
        {
            id: "portfolio-celebration-object",
            title: "Celebration object composition",
            year: "2026",
            medium: "Gift composition",
            size: "Studio arrangement",
            description: "A bright object study combining handmade texture, color, and a gift-ready sense of occasion.",
            imageUrl: "assets/maryilu-editorial-store-hero.png"
        }
    ];

    const socialLinks = [
        {
            id: "instagram",
            label: { en: "Instagram", es: "Instagram" },
            tag: { en: "@marialuisas_arttt", es: "@marialuisas_arttt" },
            handle: "@marialuisas_arttt",
            href: "https://www.instagram.com/marialuisas_arttt/",
            icon: "IG"
        },
        {
            id: "tiktok",
            label: { en: "TikTok", es: "TikTok" },
            tag: { en: "Main account", es: "Cuenta principal" },
            handle: "TikTok",
            href: "",
            icon: "TT"
        },
        {
            id: "tiktok-art",
            label: { en: "TikTok", es: "TikTok" },
            tag: { en: "Art account", es: "Cuenta de arte" },
            handle: "TikTok art",
            href: "",
            icon: "ART"
        },
        {
            id: "tiktok-etsy",
            label: { en: "TikTok", es: "TikTok" },
            tag: { en: "Etsy", es: "Etsy" },
            handle: "TikTok Etsy",
            href: "",
            icon: "ETSY"
        }
    ];

    const copy = {
        en: {
            htmlLang: "en",
            metaTitle: "Maryilu | Custom Handmade Gifts & Art",
            metaDescription: "Custom handmade gifts and art made around your story. Order custom gift boxes, chests, bouquets, canvases, and baby shower gifts from Maryilu in Mallorca.",
            navHome: "Home",
            navProducts: "Shop",
            navProductsAvailable: "Available Art",
            navProductsCustom: "Shop",
            navGallery: "Gallery",
            navSocials: "Social",
            navPrices: "Starting Prices",
            navOrder: "Custom Orders",
            navAbout: "About",
            navPortfolio: "Portfolio",
            navPolicies: "Shipping & Policies",
            brand: "Maryilu",
            heroTitle: "Custom Art Gifts Worth Keeping",
            heroSubtitle: "One-of-one art, hand-painted chests, ribbon bouquets, canvases, and baby shower gifts made with heart in Mallorca.",
            heroPrimary: "Shop Available Art",
            heroPrimaryAvailable: "See Available Art",
            heroPrimaryCustom: "Start a Custom Gift",
            heroExplore: "Explore Gift Ideas",
            heroSecondary: "Start a Custom Gift",
            heroNote: "Handmade gift workshop in Mallorca",
            heroTrustStudio: "Handmade in Mallorca",
            heroTrustQuote: "Quote before deposit",
            heroTrustReview: "Artist-reviewed listings",
            heroProofTitle: "Made for one person, not everyone.",
            heroProofText: "Every piece is personal from start to finish.",
            heroTrustDirect: "{count} direct checkout",
            heroTrustCustom: "{count} custom ideas",
            heroTrustInstagram: "Instagram post",
            heroTrustManual: "Studio preview",
            heroMicroArtist: "Handmade in Mallorca",
            heroMicroStripe: "Quote before payment",
            heroMicroOne: "Studio examples",
            heroMicroOneLive: "Fresh Instagram work",
            heroConsoleTitle: "How the order starts",
            heroConsoleArtist: "Choose a gift direction",
            heroConsoleStripe: "Send the short brief",
            heroConsoleLock: "Maryilu confirms the price",
            commerceEyebrow: "Simple custom path",
            commerceTitle: "Choose the idea. Maryilu confirms the rest.",
            commerceText: "Browse the examples, send a short brief, and get a clear quote before any payment is needed.",
            commerceDropLabel: "Studio preview",
            commerceDropTitle: "Real pieces, used as starting points",
            commerceDropText: "The photos show Maryilu's current style. Your gift starts from that language, then becomes personal to the occasion.",
            commerceReviewTitle: "Start with a direction",
            commerceReviewText: "Pick the closest idea and share what should change.",
            commerceStripeTitle: "Get a clear quote",
            commerceStripeText: "Maryilu confirms the size, timing, and price before payment.",
            commerceLockTitle: "Then make it real",
            commerceLockText: "After approval, the piece moves into production with the agreed details.",
            commerceRailChest: "Painted chests",
            commerceRailBouquets: "Ribbon bouquets",
            commerceRailCanvases: "Custom canvases",
            commerceRailBaby: "Baby shower gifts",
            commerceRailStripe: "Custom quotes",
            commerceRailInstagram: "Studio preview",
            heroOrbitTopLabel: "New studio piece",
            heroOrbitTopTitle: "Hand-painted chest",
            heroOrbitBottomLabel: "Custom path",
            heroOrbitBottomTitle: "Quote -> deposit -> final",
            assuranceStripeTitle: "Pick the idea",
            assuranceStripeText: "Start from a chest, bouquet, canvas, or baby gift.",
            assuranceArtistTitle: "Send the story",
            assuranceArtistText: "Share the colors, occasion, person, and budget.",
            assuranceOneTitle: "Maryilu replies",
            assuranceOneText: "You get a clear direction and price before work starts.",
            assuranceCustomTitle: "Payment comes later",
            assuranceCustomText: "No checkout appears until the details are approved.",
            trustCockpitEyebrow: "Studio commerce system",
            trustCockpitTitle: "High-touch art. Payment-safe checkout.",
            trustCockpitText: "Fresh posts can feed the store, but anything payable stays artist-reviewed: quote first, clear status, then Stripe only when the details are approved.",
            trustCockpitSystemLabel: "Store system",
            trustCockpitSystemValue: "Quote-led commerce",
            trustCockpitStepOneTitle: "Artist review",
            trustCockpitStepOneText: "Maryilu confirms the design, price, and timing before payment.",
            trustCockpitStepTwoTitle: "Stripe stays gated",
            trustCockpitStepTwoText: "Buy buttons appear only for reviewed, available pieces.",
            trustCockpitStepThreeTitle: "Fresh work pipeline",
            trustCockpitStepThreeText: "Instagram posts can become inspiration after the official feed is connected.",
            signalBandEyebrow: "Recent studio work",
            signalBandTitle: "New work, clearly reviewed.",
            signalBandText: "Recent pieces and process moments show what Maryilu is making now. Anything payment-ready stays artist-approved first.",
            signalBandStepOneTitle: "Fresh from the studio",
            signalBandStepOneText: "New pieces can appear as inspiration.",
            signalBandStepTwoTitle: "Checked by Maryilu",
            signalBandStepTwoText: "Details stay reviewed before checkout.",
            signalBandStepThreeTitle: "Quote before payment",
            signalBandStepThreeText: "Custom gifts start with a clear price.",
            proofTickerStripe: "Payment after quote",
            proofTickerStripeText: "No surprise checkout",
            proofTickerArtist: "Artist-reviewed inventory",
            proofTickerArtistText: "Maria controls what can be bought",
            proofTickerInstagram: "Fresh studio work",
            proofTickerInstagramText: "Real posts can become reviewed inspiration",
            proofTickerLock: "One-of-one lock",
            proofTickerLockText: "Available, reserved, sold",
            heroArtChest: "Story engine",
            heroArtBouquet: "Ribbon power",
            heroArtCanvas: "Paint card",
            heroPrimaryShopPreview: "Explore Gift Ideas",
            categoryTitle: "Pick the build. Power it with story.",
            categoryText: "Choose a starting point and Maryilu will tune the size, style, and budget.",
            galleryTitle: "Built to feel impossible to miss.",
            galleryText: "Use these examples as direction, then request something made for your occasion.",
            shopTitle: "Gift Ideas & Custom Art",
            shopTitleAvailable: "Available Art & Custom Gifts",
            shopTitleCustom: "Gift Ideas & Custom Art",
            shopText: "One-of-one pieces and made-to-order keepsakes. Buy available art or start a custom request.",
            shopTextAvailable: "One-of-one pieces and made-to-order keepsakes. Available art is reviewed before direct checkout appears.",
            shopTextCustom: "Browse custom inspiration first. Every request starts with a clear quote before payment.",
            shopAvailable: "Available to buy",
            shopCustomOrders: "Gift ideas",
            shopSoldArchive: "Sold Archive",
            buyWithStripe: "Buy reviewed artwork",
            requestSimilar: "Request this style",
            viewOnInstagram: "View on Instagram",
            originalArtwork: "Original artwork",
            customDeposit: "Custom request",
            oneOfOne: "One of one",
            sold: "Sold",
            reserved: "Reserved",
            inquiryOnly: "Quote-led",
            shopProofInstagram: "Real Instagram studio post",
            shopProofCurated: "Curated commission style",
            shopRequestLed: "Reviewed with Maryilu first",
            shopDirectReady: "Artist-approved checkout",
            shopPriceGuideLabel: "Starting point",
            shopEmpty: "Custom orders are open now. Available originals will appear here as Maryilu releases them.",
            checkoutStarting: "Opening Stripe checkout...",
            checkoutError: "Checkout could not be started. You can still message Maryilu directly.",
            customOrderCardTitle: "Start a Custom Gift",
            customOrderCardText: "A clear path for custom gifts: idea, quote, deposit, final approval.",
            customStepQuote: "Quote approved",
            customStepDeposit: "Deposit",
            customStepFinal: "Final payment",
            customOrderCardCta: "Start a Custom Gift",
            mallorcaProofTitle: "Handmade in Mallorca",
            mallorcaProofText: "Designed, painted, and finished in Maria Luisa's studio.",
            proofTitle: "Why buyers trust Maryilu",
            proofText: "Curated studio examples, visible process, and clear payment steps show how each custom piece is handled before it becomes payment-ready.",
            proofTextLive: "Fresh Instagram posts, real studio work, visible process, and personal details make each piece feel unmistakably handmade.",
            proofStudioTitle: "Curated examples first",
            proofStudioTitleLive: "Studio-made, start to finish",
            proofStudioText: "The current images show Maryilu’s studio direction. Fresh posts can appear once they are approved.",
            proofStudioTextLive: "Every detail is designed and painted in Maria Luisa’s Mallorca studio.",
            proofReviewTitle: "Shared before it leaves the studio",
            proofReviewText: "Maryilu shows the direction, timing, and important details before a custom piece begins.",
            proofPaymentTitle: "Clear, calm ordering",
            proofPaymentText: "Custom work starts with a quote; payment links are only sent after the details are clear.",
            proofInstagramTitle: "Instagram stays fresh",
            proofInstagramText: "New studio posts can become inspiration, public portfolio updates, or reviewed shop items.",
            trustSystemEyebrow: "Buyer confidence",
            trustSystemTitle: "Clear steps before payment.",
            trustSystemText: "Studio examples, artist review, and protected payment links keep the request path clear.",
            trustSystemTextLive: "Fresh Instagram work, artist review, and protected payment links keep each handmade order easy to trust.",
            trustSystemStatusLive: "Source labeled",
            trustSystemStatusLiveConnected: "Fresh Instagram work",
            trustSystemStatusReview: "Reviewed before checkout",
            trustSystemCardProofTitle: "Source stays clear",
            trustSystemCardProofTitleLive: "Fresh Instagram work",
            trustSystemCardProofText: "Preview examples stay labeled until fresh Instagram posts are approved.",
            trustSystemCardProofTextLive: "Recent posts and studio images show the work is current without forcing every piece into instant checkout.",
            trustSystemCardPaymentTitle: "Safe payment links",
            trustSystemCardPaymentText: "Custom gifts use a quote first, then Stripe deposit and final payment links when the order is ready.",
            trustSystemCardInventoryTitle: "Clear artwork status",
            trustSystemCardInventoryText: "One-of-one pieces stay marked as available, request-only, reserved, or sold.",
            instagramProofTitle: "New work appears on Instagram first",
            instagramProofText: "Follow @marialuisas_arttt for the latest pieces, studio moments, and custom gift inspiration.",
            trustTitle: "How ordering works",
            trustText: "Start with the person and occasion. Maryilu replies with direction, timing, and a clear price before payment.",
            trustCta: "Start a custom order",
            trustBentoKicker: "Confidence path",
            trustWideTitle: "Made for one person, not everyone.",
            trustWideText: "Each piece starts with the recipient, the occasion, the colors, the inside jokes, and the little emotional details that make a gift land.",
            trustHandmadeTitle: "Send the idea",
            trustHandmadeText: "Tell Maryilu who it is for, the occasion, the timeline, and the budget.",
            trustPaymentTitle: "Approve the quote",
            trustPaymentText: "You get a direction, timing, and final price before handmade work begins.",
            trustRecentTitle: "Pay safely",
            trustRecentText: "Deposits and final payments use Stripe when the order is ready.",
            trustSignalMaker: "Studio made",
            trustSignalMakerText: "Handmade in Mallorca",
            trustSignalQuote: "Quote first",
            trustSignalQuoteText: "Clear price before payment",
            trustSignalFresh: "Fresh work",
            trustSignalFreshText: "Instagram keeps the studio current",
            trustCheckoutTitle: "No checkout dead ends",
            trustCheckoutText: "If a piece is not priced for direct checkout, the site points you to a custom request instead.",
            signalAvailableTitle: "Available art",
            signalAvailableText: "Buy one-of-one pieces when listed",
            signalCustomTitle: "Custom gifts",
            signalCustomText: "Start with an idea and budget",
            signalQuoteTitle: "Quote first",
            signalQuoteText: "Approve price before deposit",
            signalProofTitle: "Recent work",
            signalProofText: "Studio posts keep the site current",
            automationTitle: "Recent studio work stays connected to the shop.",
            automationText: "When Maria posts new work, the site can show it as proof, inspiration, or reviewed shop inventory.",
            automationStep1Title: "Instagram post",
            automationStep1Text: "Fresh studio work becomes visible proof.",
            automationStep2Title: "Artist review",
            automationStep2Text: "Maryilu decides what is inspiration and what can be bought.",
            automationStep3Title: "Clear status",
            automationStep3Text: "Pieces are marked as available, request-only, reserved, or sold.",
            automationStep4Title: "Buy or request",
            automationStep4Text: "Priced work opens Stripe; custom ideas open the request form.",
            agentConsoleTitle: "Live studio signals",
            agentConsoleLine1: "new Instagram work appears as proof",
            agentConsoleLine2: "Maryilu reviews what becomes buyable",
            agentConsoleLine3: "availability stays clear: request / reserved / sold",
            engineTitle: "Buyer confidence",
            engineProofLabel: "Studio signal",
            engineProofValue: "Recent work and process",
            engineReviewLabel: "Artist review",
            engineReviewValue: "Maryilu approves the details",
            enginePaymentLabel: "Payment path",
            enginePaymentValue: "Quote first, Stripe when ready",
            engineAvailableLabel: "Ready to buy",
            engineCustomLabel: "Custom path",
            engineSourceLabel: "Proof source",
            engineGuardLabel: "Checkout guard",
            engineAgentLabel: "Feed state",
            engineAvailableValue: "{count} ready now",
            engineCustomValue: "{count} requestable ideas",
            heroHudCustomReady: "Custom orders open",
            engineSourceInstagram: "Instagram connected",
            engineSourceInstagramPending: "Instagram feed queued",
            engineSourceInstagramPreview: "Curated studio examples",
            engineSourceManual: "Curated studio preview",
            engineAgentLive: "Instagram sync live",
            engineAgentSimulated: "Studio feed",
            engineAgentPending: "Instagram feed pending",
            engineAgentPreview: "Studio feed",
            engineGuardValue: "Available -> reserved -> sold",
            engineFooter: "Studio work, artist review, and quote-first ordering keep each handmade gift clear.",
            engineFooterLive: "New Instagram work can become inspiration, portfolio content, or reviewed shop items.",
            engineFooterSimulated: "Curated studio examples stay useful while fresh Instagram posts wait for approval.",
            all: "All",
            howTitle: "The build plan",
            progressTitle: "Made with your direction, not guesswork.",
            progressText: "Custom pieces are made with your direction. I’ll ask about the person, the occasion, colors, memories, references, and style. For detailed projects, I can send progress updates so we stay aligned before the final piece is finished.",
            pricesTitle: "Starting prices",
            pricesText: "Simple starting points. Open a category for the full range.",
            addOnsTitle: "Add-ons",
            optionalDetails: "Optional details",
            viewDetails: "Details",
            shippingTitle: "Shipping from Mallorca",
            shippingIntro: "All orders are handmade in Mallorca, Spain. Pickup, local delivery, Spain shipping, EU shipping, and international quotes are available.",
            orderTitle: "Start Your Custom Gift",
            orderIntro: "Tell us the person, the occasion, and the feeling. Maryilu shapes the art around the story.",
            depositNotice: "50% deposit to begin. The final 50% is paid before pickup or shipping.",
            responseExpectation: "You’ll get an idea, timeline, and final price.",
            aboutTitle: "About Maryilu",
            aboutText1: "Maryilu makes handmade gifts for people who want a present to feel specific, emotional, and remembered.",
            aboutText2: "Each piece starts with the person: colors, memories, music, inside jokes, favorite styles, and the small details that make them feel known.",
            socialTitle: "New works appear on Instagram first",
            socialText: "Recent studio pieces and process moments from Maria's public posts.",
            socialFallbackTitle: "Studio work and Instagram",
            socialFallbackText: "Open Maria's public feed for the latest posts. Curated studio examples keep the site useful while the official feed is connected.",
            socialFallbackCardTitle: "Instagram studio feed",
            socialFallbackCardText: "The public feed is linked now; new website cards appear after the official sync is approved.",
            socialPreviewTitle: "Curated studio examples",
            socialPreviewText: "Selected studio pieces show Maryilu's current direction while new posts wait for approval.",
            socialPreviewLabel: "Studio example",
            socialPreviewNote: "Studio example",
            autoPublishNote: "Latest studio updates",
            socialFallbackLabel: "Instagram profile",
            socialFallbackCta: "Open Instagram",
            socialComingSoon: "Link soon",
            socialOpen: "Open",
            policiesTitle: "Shipping & Policies",
            policiesIntro: "The practical details, kept tucked away until you need them.",
            faqTitle: "Questions before ordering",
            finalCtaTitle: "Let’s create something unforgettable.",
            finalCtaText: "Original art. Thoughtful gifts. Lasting memories.",
            instagramCta: "Message on Instagram",
            portfolioCta: "View Art Portfolio",
            portfolioTitle: "Maryilu Art Portfolio",
            portfolioIntro: "Selected paintings, handmade visual stories, and studio studies by Maria Luisa, gathered as a quiet archive of color, memory, and handmade detail.",
            portfolioSocialTitle: "Public studio feed",
            portfolioSocialText: "Recent public posts become visible here after Instagram sync. Until then, the portfolio stays focused on curated work and a direct Instagram link.",
            portfolioAboutTitle: "About Maria Luisa",
            portfolioAboutText: "Maria Luisa Matees creates expressive paintings and handmade pieces under the Maryilu name. Her work is personal, colorful, and emotionally specific.",
            commandBarTitle: "Gifts that carry meaning",
            commandBarText: "One-of-one art, made with heart in Mallorca.",
            footerText: "Custom handmade gifts and art made around your story.",
            priceFromLabel: "Starts",
            sizeLabel: "Size",
            timeLabel: "Timeline",
            shippingLabel: "Shipping",
            bestForLabel: "Best for",
            name: "Name",
            email: "Email (optional)",
            phone: "Best contact (WhatsApp or email)",
            instagram: "Instagram username (optional)",
            preferredLanguage: "Preferred language",
            countryCity: "Country / city (optional)",
            productCategory: "Product category",
            productTier: "Specific product/tier if known",
            occasion: "Occasion (optional)",
            deadline: "Deadline/date needed",
            budget: "Budget range",
            recipient: "Short idea / who is it for?",
            ageRange: "Recipient age range",
            interests: "Recipient interests/hobbies",
            colors: "Favorite colors/style",
            includeThemes: "Themes to include",
            avoidThemes: "Themes to avoid",
            memories: "Personal memories/inside jokes",
            songQuote: "Song/quote/text to include",
            references: "Reference photos or links",
            referenceLinks: "Reference links, photos, or inspiration boards (optional)",
            pickupShipping: "Pickup/shipping preference",
            involvement: "Creative involvement",
            notes: "Anything else Maryilu should know? (optional)",
            consent: "I consent to be contacted about this custom order request.",
            submit: "Send Request",
            submitting: "Sending...",
            success: "Thank you. Maryilu will reply with an idea, timeline, and final price.",
            error: "Something went wrong sending the request. Please try again or message Maryilu on Instagram.",
            requiredNote: "Start with only the essentials. Maryilu can ask for the rest.",
            quickBriefTime: "2 minute",
            quickBriefTimeText: "quick brief",
            quickBriefQuote: "Quote first",
            quickBriefQuoteText: "no payment now",
            quickBriefOptional: "Details later",
            quickBriefOptionalText: "photos by Instagram",
            formContactTitle: "Start here",
            formContactHint: "Name plus one reliable way to reply.",
            formGiftTitle: "Gift direction",
            formGiftHint: "Enough to shape the first quote.",
            formCreativeTitle: "Add more detail",
            formCreativeHint: "Optional contact, shipping, references, and style notes",
            fileHelp: "Share photo references as links or by Instagram after Maryilu replies.",
            privacyNote: "Your details are used only to reply about this request. Share photo references as links or by Instagram after Maryilu replies.",
            safetyNote: "Baby gifts are decorative and not toys.",
            extraItemsNote: "Purchased items inside boxes/chests are quoted separately."
        },
        es: {
            htmlLang: "es",
            metaTitle: "Maryilu | Regalos personalizados y arte hecho a mano",
            metaDescription: "Regalos personalizados y arte hecho a mano alrededor de tu historia. Encarga cajas, cofres, ramos, lienzos y regalos para celebraciones de bebé con Maryilu en Mallorca.",
            navHome: "Inicio",
            navProducts: "Tienda",
            navProductsAvailable: "Arte disponible",
            navProductsCustom: "Tienda",
            navGallery: "Galería",
            navSocials: "Social",
            navPrices: "Precios iniciales",
            navOrder: "Pedidos personalizados",
            navAbout: "Sobre Maryilu",
            navPortfolio: "Portafolio",
            navPolicies: "Envíos y políticas",
            brand: "Maryilu",
            heroTitle: "Regalos artísticos para guardar",
            heroSubtitle: "Arte único, cofres pintados, ramos de cinta, lienzos y regalos para celebraciones de bebé hechos con corazón en Mallorca.",
            heroPrimary: "Comprar arte disponible",
            heroPrimaryAvailable: "Ver arte disponible",
            heroPrimaryCustom: "Empezar regalo personalizado",
            heroExplore: "Explorar ideas de regalo",
            heroSecondary: "Empezar regalo personalizado",
            heroNote: "Taller hecho a mano en Mallorca",
            heroTrustStudio: "Hecho a mano en Mallorca",
            heroTrustQuote: "Presupuesto antes del depósito",
            heroTrustReview: "Piezas revisadas",
            heroProofTitle: "Hecho para una persona, no para todo el mundo.",
            heroProofText: "Cada pieza es personal de principio a fin.",
            heroTrustDirect: "{count} compra directa",
            heroTrustCustom: "{count} ideas personalizadas",
            heroTrustInstagram: "Post de Instagram",
            heroTrustManual: "Vista previa del estudio",
            heroMicroArtist: "Hecho a mano en Mallorca",
            heroMicroStripe: "Presupuesto antes de pagar",
            heroMicroOne: "Ejemplos del estudio",
            heroMicroOneLive: "Trabajo reciente de Instagram",
            heroConsoleTitle: "Cómo empieza el pedido",
            heroConsoleArtist: "Elige una dirección de regalo",
            heroConsoleStripe: "Envía el brief corto",
            heroConsoleLock: "Maryilu confirma el precio",
            commerceEyebrow: "Camino simple para personalizados",
            commerceTitle: "Elige la idea. Maryilu confirma el resto.",
            commerceText: "Mira los ejemplos, envía un brief corto y recibe un presupuesto claro antes de cualquier pago.",
            commerceDropLabel: "Vista previa del estudio",
            commerceDropTitle: "Piezas reales como punto de partida",
            commerceDropText: "Las fotos muestran el estilo actual de Maryilu. Tu regalo parte de ese lenguaje y se vuelve personal para la ocasión.",
            commerceReviewTitle: "Empieza con una dirección",
            commerceReviewText: "Elige la idea más cercana y cuenta qué debería cambiar.",
            commerceStripeTitle: "Recibe un presupuesto claro",
            commerceStripeText: "Maryilu confirma tamaño, tiempos y precio antes del pago.",
            commerceLockTitle: "Luego se hace real",
            commerceLockText: "Después de aprobarlo, la pieza pasa a producción con los detalles acordados.",
            commerceRailChest: "Cofres pintados",
            commerceRailBouquets: "Ramos de cinta",
            commerceRailCanvases: "Lienzos personalizados",
            commerceRailBaby: "Regalos baby shower",
            commerceRailStripe: "Presupuestos personalizados",
            commerceRailInstagram: "Vista previa del estudio",
            heroOrbitTopLabel: "Nueva pieza del estudio",
            heroOrbitTopTitle: "Cofre pintado a mano",
            heroOrbitBottomLabel: "Camino personalizado",
            heroOrbitBottomTitle: "Presupuesto -> depósito -> final",
            assuranceStripeTitle: "Elige la idea",
            assuranceStripeText: "Empieza con un cofre, ramo, lienzo o regalo de bebé.",
            assuranceArtistTitle: "Cuenta la historia",
            assuranceArtistText: "Comparte colores, ocasión, persona y presupuesto.",
            assuranceOneTitle: "Maryilu responde",
            assuranceOneText: "Recibes dirección y precio claro antes de empezar.",
            assuranceCustomTitle: "El pago viene después",
            assuranceCustomText: "No aparece checkout hasta aprobar los detalles.",
            trustCockpitEyebrow: "Sistema de comercio del estudio",
            trustCockpitTitle: "Arte cercano. Checkout seguro.",
            trustCockpitText: "Los posts recientes pueden alimentar la tienda, pero todo lo que se pueda pagar queda revisado por la artista: presupuesto primero, estado claro y Stripe solo cuando los detalles están aprobados.",
            trustCockpitSystemLabel: "Sistema de tienda",
            trustCockpitSystemValue: "Compra con presupuesto",
            trustCockpitStepOneTitle: "Revisión de la artista",
            trustCockpitStepOneText: "Maryilu confirma diseño, precio y tiempos antes del pago.",
            trustCockpitStepTwoTitle: "Stripe protegido",
            trustCockpitStepTwoText: "Los botones de compra aparecen solo en piezas revisadas y disponibles.",
            trustCockpitStepThreeTitle: "Pipeline de trabajo nuevo",
            trustCockpitStepThreeText: "Los posts de Instagram pueden inspirar pedidos cuando el feed oficial esté conectado.",
            signalBandEyebrow: "Trabajo reciente del estudio",
            signalBandTitle: "Trabajo nuevo, revisado con calma.",
            signalBandText: "Las piezas recientes y momentos del proceso muestran lo que Maryilu está creando. Todo lo listo para pago queda aprobado por la artista primero.",
            signalBandStepOneTitle: "Fresco del estudio",
            signalBandStepOneText: "Las piezas nuevas pueden inspirar el pedido.",
            signalBandStepTwoTitle: "Revisado por Maryilu",
            signalBandStepTwoText: "Los detalles se revisan antes del checkout.",
            signalBandStepThreeTitle: "Presupuesto antes de pagar",
            signalBandStepThreeText: "Los regalos personalizados empiezan con precio claro.",
            proofTickerStripe: "Pago despues del presupuesto",
            proofTickerStripeText: "Sin checkout sorpresa",
            proofTickerArtist: "Inventario revisado por la artista",
            proofTickerArtistText: "María controla qué se puede comprar",
            proofTickerInstagram: "Trabajo reciente del estudio",
            proofTickerInstagramText: "Los posts reales pueden inspirar piezas revisadas",
            proofTickerLock: "Bloqueo de pieza única",
            proofTickerLockText: "Disponible, reservado, vendido",
            heroArtChest: "Motor de historia",
            heroArtBouquet: "Poder de cinta",
            heroArtCanvas: "Tarjeta pintada",
            heroPrimaryShopPreview: "Explorar ideas",
            categoryTitle: "Elige el formato. Dale energía con historia.",
            categoryText: "Escoge un punto de partida y Maryilu ajusta tamaño, estilo y presupuesto.",
            galleryTitle: "Regalos hechos para llamar la atención.",
            galleryText: "Usa estos ejemplos como dirección y pide algo creado para tu ocasión.",
            shopTitle: "Ideas de regalo y arte personalizado",
            shopTitleAvailable: "Arte disponible y regalos personalizados",
            shopTitleCustom: "Ideas de regalo y arte personalizado",
            shopText: "Piezas únicas y regalos hechos por encargo. Compra arte disponible o empieza una solicitud personalizada.",
            shopTextAvailable: "Piezas únicas y regalos por encargo. El arte disponible se revisa antes de mostrar compra directa.",
            shopTextCustom: "Explora inspiración personalizada. Cada pedido empieza con un presupuesto claro antes de pagar.",
            shopAvailable: "Disponible para comprar",
            shopCustomOrders: "Ideas de regalo",
            shopSoldArchive: "Archivo vendido",
            buyWithStripe: "Comprar obra revisada",
            requestSimilar: "Pedir este estilo",
            viewOnInstagram: "Ver en Instagram",
            originalArtwork: "Obra original",
            customDeposit: "Solicitud personalizada",
            oneOfOne: "Pieza única",
            sold: "Vendido",
            reserved: "Reservado",
            inquiryOnly: "Con presupuesto",
            shopProofInstagram: "Post real del estudio en Instagram",
            shopProofCurated: "Estilo curado por encargo",
            shopRequestLed: "Revisado primero con Maryilu",
            shopDirectReady: "Checkout aprobado por la artista",
            shopPriceGuideLabel: "Punto de partida",
            shopEmpty: "Los pedidos personalizados están abiertos. Las obras originales aparecerán aquí cuando Maryilu las publique.",
            checkoutStarting: "Abriendo checkout de Stripe...",
            checkoutError: "No se pudo abrir el checkout. Todavía puedes escribir a Maryilu directamente.",
            customOrderCardTitle: "Empezar un regalo personalizado",
            customOrderCardText: "Un camino claro para regalos personalizados: idea, presupuesto, depósito y aprobación final.",
            customStepQuote: "Presupuesto aprobado",
            customStepDeposit: "Depósito",
            customStepFinal: "Pago final",
            customOrderCardCta: "Empezar regalo personalizado",
            mallorcaProofTitle: "Hecho a mano en Mallorca",
            mallorcaProofText: "Diseñado, pintado y terminado en el estudio de María Luisa.",
            proofTitle: "Por qué compradores confían en Maryilu",
            proofText: "Ejemplos curados del estudio, proceso visible y pasos claros de pago muestran cómo se gestiona cada pieza antes de quedar lista para pagar.",
            proofTextLive: "Posts recientes de Instagram, trabajo real de estudio, proceso visible y detalles personales hacen que cada pieza se sienta claramente handmade.",
            proofStudioTitle: "Ejemplos curados primero",
            proofStudioTitleLive: "Hecho en estudio, de principio a fin",
            proofStudioText: "Las imágenes actuales muestran la dirección de estudio de Maryilu. Los posts recientes pueden aparecer cuando estén aprobados.",
            proofStudioTextLive: "Cada detalle se diseña y pinta en el estudio de María Luisa en Mallorca.",
            proofReviewTitle: "Compartido antes de salir del estudio",
            proofReviewText: "Maryilu muestra la dirección, el plazo y los detalles importantes antes de empezar una pieza personalizada.",
            proofPaymentTitle: "Pedido claro y tranquilo",
            proofPaymentText: "El trabajo personalizado empieza con presupuesto; los enlaces de pago se envian solo cuando los detalles estan claros.",
            proofInstagramTitle: "Instagram siempre fresco",
            proofInstagramText: "Los posts nuevos pueden ser inspiración, contenido de portfolio o piezas revisadas para la tienda.",
            trustSystemEyebrow: "Confianza para comprar",
            trustSystemTitle: "Pasos claros antes de pagar.",
            trustSystemText: "Ejemplos del estudio, revisión de la artista y enlaces de pago protegidos mantienen claro el pedido.",
            trustSystemTextLive: "Trabajo reciente de Instagram, revisión de la artista y enlaces de pago protegidos hacen que cada pedido sea fácil de confiar.",
            trustSystemStatusLive: "Fuente marcada",
            trustSystemStatusLiveConnected: "Trabajo reciente de Instagram",
            trustSystemStatusReview: "Revisado antes del checkout",
            trustSystemCardProofTitle: "Fuente clara",
            trustSystemCardProofTitleLive: "Trabajo reciente de Instagram",
            trustSystemCardProofText: "Los ejemplos de vista previa quedan marcados hasta aprobar posts recientes de Instagram.",
            trustSystemCardProofTextLive: "Los posts recientes y las imágenes del estudio muestran trabajo actual sin convertir cada pieza en compra inmediata.",
            trustSystemCardPaymentTitle: "Enlaces de pago seguros",
            trustSystemCardPaymentText: "Los regalos personalizados empiezan con presupuesto y luego usan depósito y pago final por Stripe cuando el pedido está listo.",
            trustSystemCardInventoryTitle: "Estado claro de la obra",
            trustSystemCardInventoryText: "Las piezas únicas se mantienen como disponibles, por solicitud, reservadas o vendidas.",
            instagramProofTitle: "El trabajo nuevo aparece primero en Instagram",
            instagramProofText: "Sigue @marialuisas_arttt para ver las piezas, momentos del estudio e inspiración de regalos personalizados.",
            trustTitle: "Cómo funciona el pedido",
            trustText: "Empieza con la persona y la ocasión. Maryilu responde con dirección, plazo y precio claro antes del pago.",
            trustCta: "Empezar pedido personalizado",
            trustBentoKicker: "Camino de confianza",
            trustWideTitle: "Hecho para una persona, no para todo el mundo.",
            trustWideText: "Cada pieza empieza con quien la recibe, la ocasión, los colores, las bromas internas y los pequeños detalles emocionales que hacen que el regalo llegue.",
            trustHandmadeTitle: "Envía la idea",
            trustHandmadeText: "Cuenta para quién es, la ocasión, el plazo y el presupuesto.",
            trustPaymentTitle: "Aprueba el presupuesto",
            trustPaymentText: "Recibes dirección, plazo y precio final antes de empezar el trabajo handmade.",
            trustRecentTitle: "Paga seguro",
            trustRecentText: "Los depósitos y pagos finales usan Stripe cuando el pedido está listo.",
            trustSignalMaker: "Hecho en estudio",
            trustSignalMakerText: "Hecho a mano en Mallorca",
            trustSignalQuote: "Presupuesto primero",
            trustSignalQuoteText: "Precio claro antes de pagar",
            trustSignalFresh: "Trabajo reciente",
            trustSignalFreshText: "Instagram mantiene el estudio actualizado",
            trustCheckoutTitle: "Sin callejones sin salida",
            trustCheckoutText: "Si una pieza no tiene precio para compra directa, la web te dirige a una solicitud personalizada.",
            signalAvailableTitle: "Arte disponible",
            signalAvailableText: "Compra piezas únicas cuando estén listadas",
            signalCustomTitle: "Regalos personalizados",
            signalCustomText: "Empieza con una idea y presupuesto",
            signalQuoteTitle: "Presupuesto primero",
            signalQuoteText: "Aprueba el precio antes del depósito",
            signalProofTitle: "Trabajo reciente",
            signalProofText: "Los posts del estudio mantienen la web actual",
            automationTitle: "El trabajo reciente del estudio sigue conectado a la tienda.",
            automationText: "Cuando María publica trabajo nuevo, la web puede mostrarlo como prueba, inspiración o inventario revisado.",
            automationStep1Title: "Post de Instagram",
            automationStep1Text: "El trabajo reciente aparece como prueba visible.",
            automationStep2Title: "Revisión de artista",
            automationStep2Text: "Maryilu decide qué es inspiración y qué se puede comprar.",
            automationStep3Title: "Estado claro",
            automationStep3Text: "Las piezas se marcan como disponibles, por solicitud, reservadas o vendidas.",
            automationStep4Title: "Comprar o pedir",
            automationStep4Text: "Las piezas con precio abren Stripe; las ideas personalizadas abren el formulario.",
            agentConsoleTitle: "Señales del estudio",
            agentConsoleLine1: "el trabajo nuevo aparece como prueba",
            agentConsoleLine2: "Maryilu revisa qué se puede comprar",
            agentConsoleLine3: "estado claro: solicitud / reservado / vendido",
            engineTitle: "Confianza para comprar",
            engineProofLabel: "Señal del estudio",
            engineProofValue: "Trabajo reciente y proceso",
            engineReviewLabel: "Revisión de artista",
            engineReviewValue: "Maryilu aprueba los detalles",
            enginePaymentLabel: "Camino de pago",
            enginePaymentValue: "Presupuesto primero, Stripe cuando esté listo",
            engineAvailableLabel: "Listo para comprar",
            engineCustomLabel: "Camino personalizado",
            engineSourceLabel: "Fuente de prueba",
            engineGuardLabel: "Protección checkout",
            engineAgentLabel: "Estado del feed",
            engineAvailableValue: "{count} listas ahora",
            engineCustomValue: "{count} ideas para pedir",
            heroHudCustomReady: "Pedidos abiertos",
            engineSourceInstagram: "Instagram conectado",
            engineSourceInstagramPending: "Feed de Instagram en espera",
            engineSourceInstagramPreview: "Ejemplos curados del estudio",
            engineSourceManual: "Vista previa curada del estudio",
            engineAgentLive: "Sincronización Instagram activa",
            engineAgentSimulated: "Feed del estudio",
            engineAgentPending: "Feed de Instagram pendiente",
            engineAgentPreview: "Feed del estudio",
            engineGuardValue: "Disponible -> reservado -> vendido",
            engineFooter: "Trabajo de estudio, revisión de artista y presupuesto primero mantienen cada regalo claro.",
            engineFooterLive: "El trabajo nuevo de Instagram puede ser inspiración, contenido de portfolio o pieza revisada.",
            engineFooterSimulated: "Los ejemplos curados del estudio siguen siendo utiles mientras los posts recientes esperan aprobacion.",
            all: "Todo",
            howTitle: "El plan del pedido",
            progressTitle: "Hecho con tu dirección, no a ciegas.",
            progressText: "Las piezas personalizadas se hacen con tu dirección. Te preguntaré por la persona, la ocasión, colores, recuerdos, referencias y estilo. Para proyectos detallados, puedo enviar avances para mantenernos alineados antes de terminar la pieza final.",
            pricesTitle: "Precios iniciales",
            pricesText: "Puntos de partida simples. Abre una categoría para ver opciones.",
            addOnsTitle: "Extras",
            optionalDetails: "Detalles opcionales",
            viewDetails: "Detalles",
            shippingTitle: "Envíos desde Mallorca",
            shippingIntro: "Todos los pedidos se hacen a mano en Mallorca, España. Hay recogida, entrega local, envío a España, envío UE y presupuestos internacionales.",
            orderTitle: "Empieza tu regalo personalizado",
            orderIntro: "Cuenta la persona, la ocasión y la emoción. Maryilu crea el arte alrededor de la historia.",
            depositNotice: "50% de depósito para empezar. El 50% final se paga antes de recogida o envío.",
            responseExpectation: "Recibirás idea, plazo y precio final.",
            aboutTitle: "Sobre Maryilu",
            aboutText1: "Maryilu crea regalos hechos a mano para que un detalle se sienta personal, emocional y recordado.",
            aboutText2: "Cada pieza empieza con la persona: colores, recuerdos, música, bromas internas, estilos favoritos y pequeños detalles que la hacen sentir conocida.",
            socialTitle: "El trabajo nuevo aparece primero en Instagram",
            socialText: "Piezas recientes y momentos de proceso desde los posts públicos de María.",
            socialFallbackTitle: "Trabajo de estudio e Instagram",
            socialFallbackText: "Abre el feed publico de Maria para ver los posts recientes. Los ejemplos curados mantienen la web util mientras se conecta el feed oficial.",
            socialFallbackCardTitle: "Feed de estudio en Instagram",
            socialFallbackCardText: "El feed publico ya esta enlazado; las tarjetas nuevas apareceran cuando la sync oficial este aprobada.",
            socialPreviewTitle: "Ejemplos curados del estudio",
            socialPreviewText: "Piezas seleccionadas del estudio muestran la direccion actual de Maryilu mientras los posts nuevos esperan aprobacion.",
            socialPreviewLabel: "Ejemplo del estudio",
            socialPreviewNote: "Ejemplo del estudio",
            autoPublishNote: "Actualizaciones recientes del estudio",
            socialFallbackLabel: "Perfil de Instagram",
            socialFallbackCta: "Abrir Instagram",
            socialComingSoon: "Link pronto",
            socialOpen: "Abrir",
            policiesTitle: "Envíos y políticas",
            policiesIntro: "Los detalles prácticos, guardados hasta que los necesites.",
            faqTitle: "Preguntas antes de pedir",
            finalCtaTitle: "Creemos algo inolvidable.",
            finalCtaText: "Arte original. Regalos con intención. Recuerdos duraderos.",
            instagramCta: "Escribir por Instagram",
            portfolioCta: "Ver portfolio artístico",
            portfolioTitle: "Portfolio de arte Maryilu",
            portfolioIntro: "Pinturas seleccionadas, historias visuales hechas a mano y estudios de Maria Luisa reunidos como un archivo tranquilo de color, memoria y detalle.",
            portfolioSocialTitle: "Feed publico del estudio",
            portfolioSocialText: "Los posts publicos recientes apareceran aqui despues de la sync de Instagram. Hasta entonces, el portfolio se centra en obra curada y enlace directo a Instagram.",
            portfolioAboutTitle: "Sobre Maria Luisa",
            portfolioAboutText: "Maria Luisa Matees crea pinturas expresivas y piezas handmade bajo el nombre Maryilu. Su trabajo es personal, colorido y emocionalmente especifico.",
            commandBarTitle: "Regalos con significado",
            commandBarText: "Arte único, hecho con corazón en Mallorca.",
            footerText: "Regalos personalizados y arte hecho a mano alrededor de tu historia.",
            priceFromLabel: "Desde",
            sizeLabel: "Tamaño",
            timeLabel: "Plazo",
            shippingLabel: "Envío",
            bestForLabel: "Ideal para",
            name: "Nombre",
            email: "Email (opcional)",
            phone: "Mejor contacto (WhatsApp o email)",
            instagram: "Usuario de Instagram (opcional)",
            preferredLanguage: "Idioma preferido",
            countryCity: "País / ciudad (opcional)",
            productCategory: "Categoría de producto",
            productTier: "Producto/tamaño si lo sabes",
            occasion: "Ocasión (opcional)",
            deadline: "Fecha límite/cuando lo necesitas",
            budget: "Presupuesto",
            recipient: "Idea corta / ¿para quién es?",
            ageRange: "Edad aproximada",
            interests: "Intereses/hobbies",
            colors: "Colores/estilo favoritos",
            includeThemes: "Temas a incluir",
            avoidThemes: "Temas a evitar",
            memories: "Recuerdos/bromas internas",
            songQuote: "Canción/frase/texto a incluir",
            references: "Fotos o links de referencia",
            referenceLinks: "Links, fotos o tableros de inspiración (opcional)",
            pickupShipping: "Preferencia de recogida/envío",
            involvement: "Participación creativa",
            notes: "¿Algo más que Maryilu deba saber? (opcional)",
            consent: "Acepto que me contacten sobre esta solicitud de pedido personalizado.",
            submit: "Enviar solicitud",
            submitting: "Enviando...",
            success: "Gracias. Maryilu responderá con idea, plazo y precio final.",
            error: "Algo falló al enviar la solicitud. Inténtalo otra vez o escribe a Maryilu por Instagram.",
            requiredNote: "Empieza solo con lo esencial. Maryilu puede pedir el resto.",
            quickBriefTime: "2 minutos",
            quickBriefTimeText: "brief rapido",
            quickBriefQuote: "Presupuesto primero",
            quickBriefQuoteText: "sin pago ahora",
            quickBriefOptional: "Detalles despues",
            quickBriefOptionalText: "fotos por Instagram",
            formContactTitle: "Empieza aquí",
            formContactHint: "Nombre y una forma fiable de responder.",
            formGiftTitle: "Dirección del regalo",
            formGiftHint: "Suficiente para preparar el primer presupuesto.",
            formCreativeTitle: "Añadir más detalle",
            formCreativeHint: "Contacto opcional, envío, referencias y estilo",
            fileHelp: "Comparte referencias como links o por Instagram cuando Maryilu responda.",
            privacyNote: "Tus datos se usan solo para responder sobre esta solicitud. Comparte fotos de referencia como links o por Instagram cuando Maryilu responda.",
            safetyNote: "Los regalos bebé son decorativos, no juguetes.",
            extraItemsNote: "Los artículos comprados dentro de cajas/cofres se presupuestan aparte."
        }
    };

    const selectOptions = {
        productCategories: [
            { value: "Custom Canvas", label: { en: "Custom Canvas", es: "Lienzo personalizado" } },
            { value: "Handmade Flower Bouquet", label: { en: "Handmade Flower Bouquet", es: "Ramo de flores hecho a mano" } },
            { value: "Custom Gift Box / Chest", label: { en: "Custom Gift Box / Chest", es: "Caja / cofre personalizado" } },
            { value: "Birthday Box", label: { en: "Birthday Box", es: "Caja de cumpleaños" } },
            { value: "Baby Shower Gift", label: { en: "Baby Shower Gift", es: "Regalo baby shower" } },
            { value: "I’m not sure yet", label: { en: "I’m not sure yet", es: "Aún no estoy seguro/a" } }
        ],
        budgets: [
            "Under €60",
            "€60-€99",
            "€100-€149",
            "€150-€249",
            "€250-€399",
            "€400+",
            "I need help choosing"
        ],
        deadlines: [
            { value: "No rush", label: { en: "No rush", es: "Sin prisa" } },
            { value: "Within 2 weeks", label: { en: "Within 2 weeks", es: "En 2 semanas" } },
            { value: "Within 1 week", label: { en: "Within 1 week", es: "En 1 semana" } },
            { value: "Within 3-5 days", label: { en: "Within 3-5 days", es: "En 3-5 días" } },
            { value: "Urgent / rush order", label: { en: "Urgent / rush order", es: "Urgente" } }
        ],
        involvement: [
            { value: "I trust Maryilu creatively", label: { en: "I trust Maryilu creatively", es: "Confío creativamente en Maryilu" } },
            { value: "I want to approve the direction before she starts", label: { en: "I want to approve the direction before she starts", es: "Quiero aprobar la dirección antes de que empiece" } },
            { value: "I want progress updates during the process", label: { en: "I want progress updates during the process", es: "Quiero avances durante el proceso" } },
            { value: "I need a very specific design followed closely", label: { en: "I need a very specific design followed closely", es: "Necesito que siga un diseño muy especifico" } }
        ],
        pickupShipping: [
            { value: "Mallorca pickup", label: { en: "Mallorca pickup", es: "Recogida en Mallorca" } },
            { value: "Mallorca local delivery", label: { en: "Mallorca local delivery", es: "Entrega local en Mallorca" } },
            { value: "Spain shipping", label: { en: "Spain shipping", es: "Envío a España" } },
            { value: "EU shipping", label: { en: "EU shipping", es: "Envío UE" } },
            { value: "International quote", label: { en: "International quote", es: "Presupuesto internacional" } },
            { value: "I’m not sure yet", label: { en: "I’m not sure yet", es: "Aún no estoy seguro/a" } }
        ]
    };

    const howItWorks = [
        { en: "Share the person, occasion, budget, and deadline.", es: "Comparte persona, ocasión, presupuesto y fecha." },
        { en: "Maryilu suggests a direction and final price.", es: "Maryilu propone dirección y precio final." },
        { en: "A 50% deposit reserves the handmade work.", es: "El depósito del 50% reserva el trabajo handmade." },
        { en: "The final payment is made before pickup or shipping.", es: "El pago final se hace antes de recogida o envío." }
    ];

    return {
        addOns,
        categoryMeta,
        copy,
        faqs,
        galleryPlaceholders: studioInspirationItems,
        howItWorks,
        leadStatuses,
        portfolioWorks,
        products,
        selectOptions,
        socialLinks,
        shippingPolicy
    };
})();
